name: Run tests
on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: run
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@xyro-io"

      - run: npm install
      - run: npm run test

      - name: Run coverage tests
        run: npm run coverage

      - name: Save badge.json
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: badge.json # Uploading the single file

      - name: Download badge.json
        uses: actions/download-artifact@v4
        with:
          name: coverage-badge
          path: . # Download to root

      - name: Commit and Push Coverage Badge
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin bage-test || echo "Branch bage-test does not exist"
          git checkout bage-test || git checkout -b bage-test
          git add badge.json
          git commit -m "Update coverage badge"
          git push origin bage-test
