name: Run tests
on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: run
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@xyro-io"
      - run: npm install
      - run: npm run test
      - name: coverage tests
        run: npm run coverage

      - name: save badge.json
        steps:
          - name: First
            uses: actions/upload-artifact@v4
            with:
              name: coverage-badge
              path: badge.json
          - name: Download artifact
            uses: actions/download-artifact@v4
            with:
              name: coverage-badge
            run: unzip coverage-badge.zip

      #   run: |
      #     git config --global user.name "github-actions"
      #     git config --global user.email "github-actions@github.com"
      #     git checkout bage-test
      #     git add badge.json
      #     git commit -m "Update coverage badge"
      #     git push origin bage-test
